baseURL = 'https://example.org/'
languageCode = 'nl-be'
title = 'Bijlesbureau Exponent'

disableKinds = ["taxonomy"]

[menu]
  [[menu.main]]
  identifier = "overons"
  name = "Over Ons"
  url = "#over-ons"
  weight = 1

  [[menu.main]]
  identifier = "aanbod"
  name = "Aanbod"
  url = "#aanbod"
  weight = 2

    [[menu.main]]
    identifier = "werkwijze"
    name = "Werkwijze"
    url = "#werkwijze"
    weight = 3

    [[menu.main]]
    identifier = "tarieven"
    name = "Tarieven"
    url = "#tarieven"
    weight = 4

    [[menu.main]]
    identifier = "Kalender"
    name = "Kalender"
    url = "#kalender"
    weight = 5

    [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "#contact"
    weight = 6


# for auto ID on headings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true